#' @title \code{getIntensityThreshold}
#'
#' @description \code{getIntensityThreshold} takes the output of peak calling with
#'   callOpenTiles and creates sample-tile matrices containing the signal
#'   intensity at each tile.
#'
#' @param TSAM a SummarizedExperiment object generated by MOCHA
#' @param cellPopulations vector of strings. Cell subsets found in the TSAM, or the word 'All' if all should be used.
#' @param type string. Describes the type of metric to be used. Options include median or mean.
#' @param returnPlots Boolean. Default is TRUE and returns a plot of 
#' @param verbose Set TRUE to display additional messages. Default is FALSE.
#'
#' @return plot object
#'
#' 
getIntensityThreshold <- function(TSAM, cellPopulations = 'all', type = 'mean', returnPlots = TRUE, verbose = FALSE){


    allMat <- SummarizedExperiment::assays(TSAM)

    if(tolower(cellPopulations) == 'all'){

        combMat <- do.call('cbind', as.list(allMat))

    }else if(all(cellPopulations %in% names(allMat))){

        combMat <- do.call('cbind', as.list(allMat[names(allMat) %in% cellPopulations]))
    }else{

        error('Cell populations were not all found within the MOCHA object.')
    }

    combMat[is.na(combMat)] <- 0

    ZeroSummary <- rowSums(is.na(combMat))
    

    if(tolower(type) == 'mean'){

        mean_intensities = rowMeans(combMat)

        unmixedMat = mixtools::normalmixEM(mean_intensities,
            lambda=0.5, sigma=1)

       


    }else if(tolower(type) == 'median'){

            median_intensities = rowMedians(combMat)

            unmixedMat = mixtools::normalmixEM(median_intensities,
                            lambda=0.5, sigma=1)

    }else{

        error('type is not mean or median.')
    }

    if(returnPlots){
        plot(unmixedMat, density=T, breaks=200)
    }else{

        return(tunmixedMat)
    }

}